TITLE Trabajo 1
;DESCRIPCION
;Objetivo: Primera ejecucion de masm

;Autores(s):
;		Garcia Ruiz Alejandro H.
;Semestre: 8vo Semestre ISC
;FIN DESCRIPCION
INCLUDE Irvine32.inc
.data
;Area de Declaracion de Variables

INGRESA_NUMERO_11 DB "INGRESA UN NUMERO A CHEACR", 0
RESULTADO_SI_11 DB "EL NUMERO ES PRIMO", 0
RESULTADO_NO_11 DB "EL NUMERONO ES PRIMO", 0

CONTADOR_11 DWORD 0
.code
	main11 PROC
		;Logica del Programa

		MOV EDX, OFFSET INGRESA_NUMERO_11
		CALL WRITESTRING
		CALL CRLF

		CALL READINT

		MOV EBX, EAX ;AUXILIAR PARA LA DIVISION

		MOV ECX, EAX ;PARA DEFINIR LA CANTIDAD DE DIVISIONES A REALIZAR
		DEC ECX

		CICLO:
			MOV EAX, EBX
			MOV EDX, 0
			DIV ECX
			CMP EDX, 0
			JNZ SALTA_A_LOOP

			INC CONTADOR_11
			SALTA_A_LOOP:
				LOOP CICLO

		;MOV EAX, CONTADOR_11
		;CALL WRITEDEC

		CMP CONTADOR_11, 1
		JNZ NO_ES_PRIMO
			MOV EDX, OFFSET RESULTADO_SI_11
			JMP CONTINUAR

		NO_ES_PRIMO:
			MOV EDX, OFFSET RESULTADO_NO_11

		CONTINUAR:
			CALL WRITESTRING

		exit
	main11 ENDP
	END main11